config/routes.rb
Rails.application.routes.draw do
  
  root 'profile#home'
  get 'about', to: 'profile#about'
  get 'portfolio', to: 'profile#portfolio'
  get 'projects', to: 'profile#projects'
  get 'work_exp', to: 'profile#work_exp'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/micropost.rb
class Micropost < ApplicationRecord
	belongs_to :user
	validates :content, length: {maximum: 140}, presence: true


	def details
		if self.user.nil?
			"Created on #{self.created_at.strftime("%m/%d/%Y at %H:%M")}"
		else
			"By #{self.user.name} on #{self.created_at.strftime("%m/%d/%Y at %H:%M")}"
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :microposts
	validates :name, presence: true
	validates :email, presence: true


	def details
		"Joined on #{self.created_at.strftime("%m/%d/%Y at %H:%M")}"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def home; end
  def about; end
  def portfolio; end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Artem Kyselov" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= favicon_link_tag 'icon', rel: 'shortcut icon', type: 'image/png' %>
    <%= favicon_link_tag 'icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= stylesheet_link_tag "application", media: "all" %>
    
   
    </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>"><%= image_tag("wp1.png", alt:"Artem Kyselov", :class => "navbar-icon")%> Artem Kyselov</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="<%= root_path %>"><i class="bi bi-house"></i> Home</a>
            </li>           
            <li class="nav-item">
              <a class="nav-link" href="<%= portfolio_path %>"><i class="bi bi-kanban"></i> Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= about_path %>"><i class="bi bi-briefcase"></i> About</a>
            </li>
           
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="card">
  <div class="card-header">
    <%= user.name %>
    <a href="<%= edit_user_path(@user) %>" class="btn btn-warning btn-sm float-end"><i class="bi bi-pencil-square"></i> Edit User</a>
    
  </div>
  <div class="card-body">
    <p class="card-text"><%= user.email %></p>
    <span class="badge text-bg-success"><%= pluralize(user.microposts.count,'micropost') %> created!</span>
  </div>
  <div class="card-footer">
    <%= button_to "Destroy this user", @user, method: :delete, class: "btn btn-danger btn-sm" %>
    <small class="text-body-secondary"><%= user.details %></small>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<div class="card">
  <div class="card-header">
    <i class="bi bi-journals"></i> <%= pluralize(@users.count, "USER", plural:"USERS") %>
    <a href="<%= new_user_path %>" class="btn btn-primary btn-sm float-end"><i class="bi bi-pencil-square"></i> New User</a>
  </div>
  <div class="card-body">
    <ol class="list-group list-group-numbered" id="users">
      <% @users.each do |user| %>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold"><a href="<%= user_url(user) %>"><%= user.name %></a></div>
            <%= user.email %>
          </div>
          <span class="badge text-bg-primary rounded-pill"><%= pluralize(user.microposts.count, "MicroPost", plural:"MicroPosts") %></span>
        </li>
      <% end %>
      
    </ol>

  </div>
</div>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>